import { NeuronUID } from "./neuron_tools_common";

export class NeuronDOMFactory {
    #prefix:string;


    /** Creates a DOM factory that can be used to generate consistent style elements
     * @param  {string} css_prefix A CSS prefix to give any classes generated by this factory
     */
    constructor (css_prefix:string) {
        this.#prefix = css_prefix;
    }
    /** Creates a HTML label that is linked to a specific input/other DOM element
     * @param  {string} text Label text to show
     * @param  {(HTMLInputElement|HTMLSelectElement|HTMLButtonElement|HTMLOutputElement)} input Input/other HTML element to link this label to
     * @param  {string} description Mouse-over description for this label item
     * @param  {boolean} hide_label Sets the visibility to hidden for this label if true (useful for building grid layouts with only one label but many inputs)
     */
    _create_dom_label(text:string, input:(HTMLInputElement|HTMLSelectElement|HTMLButtonElement|HTMLOutputElement), description:string = null, hide_label:boolean=false) {
        if (!input.id)
            input.id = NeuronUID();

        let l = document.createElement("label");
        l.className = `${this.#prefix}-content-label`;
        l.htmlFor = input.id;
        if(description)
            l.title = description;
        if(hide_label)
            l.style.visibility = 'hidden';

        l.appendChild(document.createTextNode(text));

        return l;
    }

    /** Creates a HTML output element
     * @param  {string} value Value string to set for this element
     */
    _create_dom_output(value:string=null) {
        let dom = document.createElement("output");
        dom.className = `${this.#prefix}-content-value ${this.#prefix}-content-value-right`;
        if(value != null)
            dom.value = value;
        return dom;
    }

    /**Creates a HTML file loader element
     * @param  {(event:Event)=>void} on_change Callback to be run when the element input is changed by the user
     * @param  {string} accepts Classifier to force the user to select specific file types
     */
    _create_dom_input_file(on_change:(event:Event) => void, accepts:string = null) {
        let dom = document.createElement("input");
        dom.type = "file";
        if(accepts != null)
            dom.accept = accepts;
        dom.className = `${this.#prefix}-content-value`;
        dom.onchange = on_change;
        return dom;
    }


    /**Creates a HTML button element
     * @param  {string} text Label string to set for this element
     * @param  {(event:Event)=>void} on_change Callback to be run when the element input is changed by the user
     */
    _create_dom_input_button(text:string, on_change:(event:Event) => void) {
        let dom = document.createElement("button");
        dom.className = `${this.#prefix}-content-value ${this.#prefix}-content-value-center`;
        dom.onclick = on_change;
        dom.appendChild(document.createTextNode(text));
        return dom;
    }

    /**Creates a HTML textbox element
     * @param  {string} value Label string to set for this element
     * @param  {(event:Event)=>void} on_change Callback to be run when the element input is changed by the user
     */
    _create_dom_input_textbox(value:string, on_change:(event:Event) => void) {
        let dom = document.createElement("input");
        dom.type = "text";
        dom.value = value.toString();
        dom.className = `${this.#prefix}-content-value`;
        dom.onchange = on_change;
        return dom;
    }

    /**Creates a HTML number scroll element
     * @param  {number} value Value to set for this element
     * @param  {(event:Event)=>void} on_change Callback to be run when the element input is changed by the user
     * @param  {number} min Minimum value that can be input for this element. Set to null for no minimum.
     * @param  {number} max Maximum value that can be input for this element Set to null for no maximum.
     * @param  {number} step Step value for scrolling/toggling for this element. Set to null for default.
     */
    _create_dom_input_number(value:number, on_change:(event:Event) => void, min:number = null, max:number = null, step:number=null) {
        let dom = document.createElement("input");
        dom.type = "number";
        if(min != null)
            dom.min = min.toString();
        if(max != null)
            dom.max = max.toString();
        if(step != null)
            dom.step = step.toString();
        dom.value = value.toString();
        dom.className = `${this.#prefix}-content-value ${this.#prefix}-content-value-right`;
        dom.onchange = on_change;
        return dom;
    }


    /**Creates a HTML slider element
     * @param  {number} value Value to set for this element
     * @param  {(event:Event)=>void} on_change Callback to be run when the element input is changed by the user
     * @param  {number} min Minimum value that can be input for this element. Set to null for no minimum.
     * @param  {number} max Maximum value that can be input for this element Set to null for no maximum.
     * @param  {number} step Step value for scrolling/toggling for this element. Set to null for default.
     */
    _create_dom_input_range(value:number, on_change:(event:Event) => void, min:number, max:number, step:number=null) {
        let dom = document.createElement("input");
        dom.type = "range";
        dom.min = min.toString();
        dom.max = max.toString();
        if(step == null)
            step = (max - min) / 100;
        dom.step = step.toString();
        dom.value = value.toString();
        dom.className = `${this.#prefix}-content-value ${this.#prefix}-content-value-right`;
        dom.onchange = on_change;
        return dom;
    }

    /**Creates a HTML checkbox element
     * @param  {boolean} checked Initial checked status of the checkbox
     * @param  {(event:Event)=>void} on_change Callback to be run when the element input is changed by the user
     */
    _create_dom_input_checkbox(checked:boolean, on_change:(event:Event) => void) {
        let dom = document.createElement("input");
        dom.type = "checkbox";
        dom.checked = checked;
        dom.className = `${this.#prefix}-content-value ${this.#prefix}-content-value-right`;
        dom.onchange = on_change;
        return dom;
    }

    /**Creates a HTML dropdown selector element.
     * @param  {string[]} options List of option values for the dropdown list to be used internally.
     * @param  {string[]} labels List of labels for the dropdown list to be shown to the user.
     * @param  {(event:Event)=>void} on_change Callback to be run when the element input is changed by the user.
     * @param  {string} selected_option Initial option to be selected. Set to null to be unselected by default.
     */
    _create_dom_input_select(options:string[], labels:string[], on_change:(event:Event) => void, selected_option:string=null) {
        let dom = document.createElement("select");

        if(options.length != labels.length)
            throw new Error(`Options list does not match labels list (${options.length} != ${labels.length})`);

        //Create and append the options
        for (let i = 0; i < options.length; i++) {
            let option = document.createElement("option");
            option.value = options[i];
            option.text = labels[i];
            if(selected_option && selected_option==options[i])
                option.selected = true;
            dom.appendChild(option);
        }
        dom.className = `${this.#prefix}-content-value`;
        dom.onchange = on_change;
        return dom;
    }
}
